services:
  whisperx-server:
    container_name: whisperx-server
    build: .
    ports:
      - "2990:2990"
    volumes:
      - ./transcriptions:/transcriptions
      - whisperx-models:/root/.cache/whisperx
      - hf-models:/root/.cache/huggingface
    env_file:
      - .env.local
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434
      - TF_FORCE_GPU_ALLOW_GROWTH=true
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_REQUIRE_CUDA=cuda>=12.2
      - CUDA_VISIBLE_DEVICES=GPU-b5864669-d804-c2f5-e94b-60885d9012af
    runtime: nvidia
    restart: unless-stopped
    depends_on:
      - qdrant
      - ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:v1.12.6
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  qdrant_data:
  ollama_data: